version: '3.8'
services:

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: betuser
      POSTGRES_PASSWORD: betpassword
      POSTGRES_DB: betsdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U betuser -d betsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  line_provider:
    build: ./line_provider
    container_name: line_provider
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  bet_maker:
    build: ./bet_maker
    container_name: bet_maker
    ports:
      - "8002:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres_db:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: betsdb
      POSTGRES_USER: betuser
      POSTGRES_PASSWORD: betpassword
